#!/usr/bin/env python3
"""
CEMENTO Rome × Seoul — Figma REST API & Slide Template Batch Generator
========================================================================
This utility connects to the Figma REST API using your Personal Access Token,
inspects a specified Template Slide Node ID, and produces an automated batch
instantiation script that duplicates your template frame 7 times and injects
the CEMENTO slide content into corresponding text layers.

Usage:
  python3 figma_api_sync.py --token <YOUR_FIGMA_PAT> --file-key <FIGMA_FILE_KEY> --template-id <NODE_ID>

Or with environment variables:
  export FIGMA_ACCESS_TOKEN="figd_..."
  export FIGMA_FILE_KEY="abc123xyz"
  export FIGMA_TEMPLATE_ID="1:2"
  python3 figma_api_sync.py
"""

import sys
import os
import json
import argparse
import urllib.request
import urllib.error

DECK_DATA_PATH = os.path.join(os.path.dirname(__file__), "deck-data.json")

def load_deck_data():
    if not os.path.exists(DECK_DATA_PATH):
        print(f"[-] Error: Could not find deck-data.json at {DECK_DATA_PATH}")
        sys.exit(1)
    with open(DECK_DATA_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def fetch_figma_node(file_key, node_id, token):
    url = f"https://api.figma.com/v1/files/{file_key}/nodes?ids={node_id}"
    req = urllib.request.Request(url, headers={
        "X-Figma-Token": token,
        "User-Agent": "Cemento-Deck-Sync/1.0"
    })
    try:
        print(f"[*] Querying Figma REST API: {url} ...")
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return data
    except urllib.error.HTTPError as e:
        print(f"[-] HTTP Error {e.code}: {e.read().decode('utf-8')}")
        return None
    except Exception as e:
        print(f"[-] Error contacting Figma API: {e}")
        return None

def extract_text_layers(node, layer_map=None):
    if layer_map is None:
        layer_map = []
    if node.get("type") == "TEXT":
        layer_map.append({
            "id": node.get("id"),
            "name": node.get("name"),
            "characters": node.get("characters", "")
        })
    for child in node.get("children", []):
        extract_text_layers(child, layer_map)
    return layer_map

def generate_figma_batch_script(file_key, template_node_id, deck_data, detected_layers=None):
    slides_json = json.dumps(deck_data["slides"], indent=2, ensure_ascii=False)
    
    script = f"""// ============================================================================
// CEMENTO × FIGMA BATCH GENERATOR FROM TEMPLATE
// Generated by figma_api_sync.py
// File Key: {file_key or 'LOCAL'} | Template Node ID: {template_node_id or 'DEFAULT'}
// ============================================================================

(async function duplicateTemplateSlides() {{
  console.log("Starting CEMENTO Batch Slide Instantiation...");

  const templateId = "{template_node_id}";
  let templateNode = null;

  if (templateId && templateId !== "NONE") {{
    templateNode = await figma.getNodeByIdAsync(templateId);
  }}

  // Fallback: If template ID is not found, use currently selected frame
  if (!templateNode && figma.currentPage.selection.length > 0) {{
    templateNode = figma.currentPage.selection[0];
    console.log("Using active selection as template:", templateNode.name);
  }}

  if (!templateNode) {{
    figma.notify("Error: Please select your template slide frame or provide a valid Template Node ID.");
    return;
  }}

  const slidesData = {slides_json};
  const createdFrames = [];
  const startX = templateNode.x + templateNode.width + 160;
  const startY = templateNode.y;
  const gap = 160;

  // Helper function to recursively find a node by name or placeholder text
  function findChild(node, predicate) {{
    if (predicate(node)) return node;
    if (node.children) {{
      for (const child of node.children) {{
        const match = findChild(child, predicate);
        if (match) return match;
      }}
    }}
    return null;
  }}

  // Helper to safely replace text while preserving or loading fonts
  async function setText(node, newText) {{
    if (!node || node.type !== "TEXT") return;
    try {{
      if (node.fontName === figma.mixed) {{
        const len = node.characters.length;
        for (let i = 0; i < len; i++) {{
          await figma.loadFontAsync(node.getRangeFontName(i, i + 1));
        }}
      }} else {{
        await figma.loadFontAsync(node.fontName);
      }}
      node.characters = String(newText);
    }} catch (err) {{
      console.warn("Font load warning for node " + node.name + ":", err);
    }}
  }}

  for (let i = 0; i < slidesData.length; i++) {{
    const slide = slidesData[i];
    const newFrame = templateNode.clone();
    newFrame.name = `[${{slide.index}}] ${{slide.category}} - ${{slide.title}}`;
    newFrame.x = startX + (i * (templateNode.width + gap));
    newFrame.y = startY;

    // Mapping layers by semantic name convention:
    // 1. Title
    const titleNode = findChild(newFrame, n => n.type === "TEXT" && (
      n.name.toLowerCase().includes("title") || 
      n.name.toLowerCase().includes("headline") ||
      n.characters.includes("TITLE")
    ));
    if (titleNode) await setText(titleNode, slide.title);

    // 2. Subtitle / Lead
    const subNode = findChild(newFrame, n => n.type === "TEXT" && (
      n.name.toLowerCase().includes("sub") || 
      n.name.toLowerCase().includes("lead") ||
      n.name.toLowerCase().includes("desc")
    ));
    if (subNode && (slide.subtitle || slide.lead)) {{
      await setText(subNode, slide.subtitle || slide.lead);
    }}

    // 3. Category / Meta Tag
    const tagNode = findChild(newFrame, n => n.type === "TEXT" && (
      n.name.toLowerCase().includes("meta") || 
      n.name.toLowerCase().includes("tag") || 
      n.name.toLowerCase().includes("category")
    ));
    if (tagNode && slide.metaTags) {{
      await setText(tagNode, slide.metaTags.join(" "));
    }}

    // 4. Slide Index Number
    const numNode = findChild(newFrame, n => n.type === "TEXT" && (
      n.name.toLowerCase().includes("num") || 
      n.name.toLowerCase().includes("page") ||
      n.characters.includes("01") ||
      n.characters.includes("01 /")
    ));
    if (numNode) await setText(numNode, `0${{i + 1}} / 07`);

    // 5. Keynote / Note
    if (slide.keyNote) {{
      const keyNoteNode = findChild(newFrame, n => n.type === "TEXT" && (
        n.name.toLowerCase().includes("note") || 
        n.name.toLowerCase().includes("author") ||
        n.name.toLowerCase().includes("founder")
      ));
      if (keyNoteNode) await setText(keyNoteNode, slide.keyNote);
    }}

    createdFrames.push(newFrame);
  }}

  figma.currentPage.selection = createdFrames;
  figma.viewport.scrollAndZoomIntoView(createdFrames);
  figma.notify(`Successfully generated ${{createdFrames.length}} CEMENTO presentation frames!`);
}})();
"""
    return script

def main():
    parser = argparse.ArgumentParser(description="Figma REST API & Template Batch Generator for CEMENTO")
    parser.add_argument("--token", default=os.getenv("FIGMA_ACCESS_TOKEN"), help="Figma Personal Access Token")
    parser.add_argument("--file-key", default=os.getenv("FIGMA_FILE_KEY"), help="Figma File Key (from URL)")
    parser.add_argument("--template-id", default=os.getenv("FIGMA_TEMPLATE_ID", "NONE"), help="Slide Template Node ID (e.g., '1:2')")
    parser.add_argument("--output", default="figma-batch-generated.js", help="Output file for generated batch script")
    args = parser.parse_args()

    deck_data = load_deck_data()
    print(f"[+] Loaded deck-data.json successfully ({len(deck_data['slides'])} slides).")

    detected_layers = []
    if args.token and args.file_key and args.template_id != "NONE":
        res = fetch_figma_node(args.file_key, args.template_id, args.token)
        if res and "nodes" in res:
            node_data = res["nodes"].get(args.template_id, {}).get("document", {})
            detected_layers = extract_text_layers(node_data)
            print(f"[+] Found {len(detected_layers)} text layers in template node {args.template_id}:")
            for lyr in detected_layers:
                print(f"    - Layer: [{lyr['name']}] (ID: {lyr['id']}) Preview: \"{lyr['characters'][:40]}...\"")
    else:
        print("[!] Note: Running in local generator mode (no Figma REST API token provided).")
        print("    A robust universal template cloner script will be generated.")

    script = generate_figma_batch_script(args.file_key, args.template_id, deck_data, detected_layers)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(script)

    print(f"[+] Successfully wrote Figma batch script to: {args.output}")
    print("\n[NEXT STEP]:")
    print(f"1. Open Figma with your slide template.")
    print(f"2. Select your template slide frame (or enter Template Node ID '{args.template_id}').")
    print(f"3. Run the script in '{args.output}' via Scripter or Figma Console.")

if __name__ == "__main__":
    main()
